puddle/conversation/urls.py
from django.urls import path

from . import views 

app_name = 'conversation'

urlpatterns = [
    path('',views.inbox , name='inbox'),
    path('<int:pk>/' , views.detail , name='detail'),
    path('new/<int:item_pk>/' , views.new_converstion , name='new'), 
]

puddle/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path 

from . import views
from .forms import LoginForm
app_name = 'core'

urlpatterns = [
    path('',views.index , name='index'),
    path('contact/',views.contact , name='contact'),
    path('signup/',views.signup , name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name = 'core/login.html',authentication_form = LoginForm) , name='login')
]

puddle/item/urls.py
from django.urls import path

from . import views


app_name = 'item'


urlpatterns = [
    path('',views.items , name='items'),
    path('new/',views.new , name='new'),
    path('<int:pk>/' , views.detail , name='detail'),
    path('<int:pk>/delete/' , views.delete , name='delete'),
    path('<int:pk>/edit/' , views.edit , name='edit'),
]

puddle/puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include
urlpatterns = [
    path('', include('core.urls')),
    path('items/' , include('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/' , include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

puddle/item/models.py
from django.contrib.auth.models import User
from django.db import models


class Area(models.Model) :
    name = models.CharField(max_length=255)

    class Meta :
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    
    def __str__(self) :
        return self.name


class Item(models.Model) :
    area = models.ForeignKey(Area , related_name = 'items' , on_delete = models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank = True , null = True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images',blank=True ,null=True)
    is_sold = models.BooleanField(default = False)
    created_by = models.ForeignKey(User,related_name = 'items',on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True)
    def __str__(self) :
            return self.name

puddle/item/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border bg-gray-900 text-white'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('area', 'name', 'description', 'price', 'image',)
        widgets = {
            'area': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': f'{INPUT_CLASSES} resize-none',  # Disable textarea resize
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': f'{INPUT_CLASSES} resize-none',  # Disable textarea resize
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

puddle/item/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render , get_object_or_404 ,redirect
from django.db.models import Q
from .models import Item , Area
from .forms import NewItemForm , EditItemForm
# Create your views here.


def items(request):
    query = request.GET.get('query' , '')
    area_id = request.GET.get('area',0)
    areas = Area.objects.all()
    items = Item.objects.filter(is_sold = False)

    if area_id :
        items = items.filter(area_id=area_id)


    if query :
        items = items.filter(Q(name__icontains = query) | Q(description__icontains = query)) 

    return render(request , 'item/items.html' , {
        'items':items,
        'query' : query, 
        'areas' : areas,
        'area_id' : int(area_id),
      })

def detail(request,pk) :
    item = get_object_or_404(Item,pk=pk)
    related_items = Item.objects.filter(area=item.area , is_sold = False).exclude(pk=pk)[0:3]


    return render(request , 'item/detail.html', {
        'item' : item,
        'related_items' : related_items
    })

@login_required
def new(request):
    if request.method == 'POST' :
        form = NewItemForm(request.POST , request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail',pk=item.id)
    else :
      form = NewItemForm()

    return render(request , 'item/form.html',{
        'form' : form,
        'title' : 'New item',
    })

@login_required
def edit(request,pk):
    item = get_object_or_404(Item , pk=pk , created_by = request.user)
    if request.method == 'POST' :
        form = EditItemForm(request.POST , request.FILES , instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail',pk=item.id)
    else :
      form = EditItemForm(instance=item)

    return render(request , 'item/form.html',{
        'form' : form,
        'title' : 'Edit item',
    })

@login_required
def delete(request,pk):
    item = get_object_or_404(Item , pk=pk , created_by = request.user)
    item.delete()

    return redirect('dashboard:index')

puddle/item/templates/item/detail.html
{% extends 'core/base.html' %} 
{% block title %} {{item.name}} {% endblock %} 

{% block content %}
<div class="grid grid-cols-5 gap-6">
  <div class="col-span-3">
    <img src="{{item.image.url}}" class="rounded-xl" alt="" />
  </div>

  <div class="col-span-2 p-6 bg-gray-900 rounded-xl text-white">
    <h1 class="mb-6 text-3xl">{{item.name}}</h1>
    <p class="text-gray-500"><strong>Price :</strong> {{item.price}}</p>
    <p class="text-gray-500">
      <strong>Seller :</strong> {{item.created_by.username}}
    </p>

    {% if item.description %}
    <p class="text-gray-300">
      <strong class="text-gray-500">Description:</strong><br />
      {{item.description}}
    </p>
    {% endif %} {% if request.user == item.created_by %}
    <div class="mt-6 p-6 bg-gray-800 rounded-xl">
      <p>This is your item!</p>
      <a
        href="{% url 'item:edit' item.id %}"
        class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-yellow-500 text-white rounded-xl hover:bg-yellow-700"
        >Edit</a
      >
      <a
        href="{% url 'item:delete' item.id %}"
        class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700"
        >Delete</a
      >
    </div>
    {% else %}
    <a
      href="{% url 'conversation:new' item.id %}"
      class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-green-500 text-white rounded-xl hover:bg-green-700"
      >Contact seller</a
    >
    {% endif %}
  </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-900 rounded-xl text-white">
  <h2 class="mb-12 text-2xl text-center">Related Properties</h2>

  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
    {% for item in related_items %}
      <a href="{% url 'item:detail' item.id %}" class="group">
        <div class="overflow-hidden aspect-w-3 aspect-h-4 bg-gray-700 rounded-lg shadow-md group-hover:shadow-xl">
          <img src="{{ item.image.url }}" class="object-cover w-full h-full" alt="{{ item.name }}">
        </div>
        <div class="mt-4 p-6 bg-gray-800 rounded-b-xl">
          <h2 class="text-xl font-semibold hover:text-gray-400 text-white-900">{{ item.name }}</h2>
          <p class="text-gray-500">Price: {{ item.price }}</p>
        </div>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock %}

puddle/item/templates/item/form.html
{% extends 'core/base.html' %}
{% block title %}New Proptery{% endblock %}

{% block content %}

<h1 class="mb-6 text-3xl text-white">New Proptery</h1>

<form action="." method="post" enctype="multipart/form-data">
  {% csrf_token %}

  <div class="space-y-4 text-white">{{ form.as_p }}</div>
  {% if form.errors or form.non_field_errors %}

  <div class="mb-3 p-6 bg-red-600 rounded-xl mt-2">
    {% for field in form %} {{ field.errors }} {% endfor %} {{ form.non_field_errors }}
  </div>

  {% endif %}
  <button class="mt-6 py-4 px-6 text-lg bg-green-500 hover:bg-green-700 rounded-xl text-white">
    Submit
  </button>
</form>

{% endblock %}

puddle/item/templates/item/items.html
{% extends 'core/base.html' %} {% block title %} Items {% endblock %} 
{% block content %}
<div class="pb-6 grid grid-cols-1 lg:grid-cols-4 gap-4 bg-gray-800 text-white">
  <div class="lg:col-span-1 p-6">
    <form action="{% url 'item:items' %}" method="get">
      <input
        name="query"
        class="w-full py-4 px-6 border rounded-xl bg-gray-900 text-white"
        type="text"
        value="{{ query }}"
        placeholder="Find a bike, a chair, or a car..."
      />
      <button
        class="mt-2 py-4 px-8 text-lg bg-green-500 text-white rounded-xl hover:bg-green-700"
      >
        Search
      </button>
    </form>

    <hr class="my-6 border-gray-700" />
    <p class="font-semibold text-gray-400">Areas</p>
    <ul>
      {% for area in  areas %}
      <li
        class="py-2 px-2 rounded-xl hover:bg-gray-500{% if area.id == area_id %} bg-gray-700 {% endif %}"
      >
        <a
          href="{% url 'item:items' %}?query={{query}}&area={{area.id}}"
          class="text-white"
          >{{area.name}}</a
        >
      </li>
      {% endfor %}
    </ul>
    <hr class="my-6 border-gray-700" />
    <p class="font-semibold text-gray-400">Clear filters</p>

    <ul>
      <li>
        <a
          href="{% url 'item:items' %}"
          class="mt-2 py-4 px-6 inline-block bg-yellow-500 text-lg rounded-xl text-white hover:bg-yellow-700"
          >Clear</a
        >
      </li>
    </ul>
  </div>
  <div class="lg:col-span-3">
    <div
      class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8"
    >
      {% for item in items %}
      <a href="{% url 'item:detail' item.id %}" class="group">
        <div
          class="overflow-hidden aspect-w-3 aspect-h-4 bg-gray-700 rounded-lg shadow-md group-hover:shadow-xl"
        >
          <img
            src="{{ item.image.url }}"
            class="object-cover w-full h-full"
            alt="{{ item.name }}"
          />
        </div>
        <div class="mt-4 p-6 bg-gray-900 rounded-b-xl">
          <h2
            class="text-xl font-semibold text-white-400 hover:text-gray-400"
          >
            {{ item.name }}
          </h2>
          <p class="text-gray-400">Price: {{ item.price }}</p>
        </div>
      </a>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}